### ISSUE TITLE
SP configuration question

### ISSUE THREAD

**Issue by Xiechengqi** [bnb-chain/greenfield-docs#42]
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/26536442/234260210-a137079c-58b7-4dcf-85cc-1793a9a1bb6d.png">
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/26536442/234260305-e272c5ff-b375-4da0-82e3-1ac4c560698a.png">

sp 的配置文件中的 [Endpoint] gateway 和发起提案 create_sp.json 中的 endpoint 是同一个吗？需要搭建一个 nginx 并将自己的域名绑定到 sp 吗？

Is the [Endpoint] gateway in the sp configuration file the same as the endpoint in the proposal create_sp.json? Need to build an nginx and bind your own domain name to sp?

**Comment by sysvm** [comment]
No, it's not the same endpoint. SP gateway is used for storage provider to store or download payload data.
